spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EduX
    username: "root"    # ✅ 여기에 실제 MySQL 사용자 이름 입력
    password: "0531"  # ✅ 여기에 실제 비밀번호 입력
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update     # create / update / validate / none 중 선택
    show-sql: true         # 콘솔에 SQL 출력
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      uri:  #잠금